site_name: DeepSentinel Python SDK
site_description: AI compliance middleware for safe LLM interactions
site_url: https://deepsentinel-ai.github.io/deepsentinel-python
site_author: DeepSentinel Team

repo_name: DeepSentinel-AI/deepsentinel-python
repo_url: https://github.com/DeepSentinel-AI/deepsentinel-python
edit_uri: edit/main/docs/

copyright: Copyright &copy; 2025 DeepSentinel

theme:
  name: material
  
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - content.tooltips
    - header.autohide
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate

  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye

plugins:
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - mkdocstrings:
      enabled: !ENV [ENABLE_MKDOCSTRINGS, true]
      default_handler: python
      handlers:
        python:
          options:
            docstring_style: google
            docstring_options:
              ignore_init_summary: true
            merge_init_into_class: true
            show_submodules: true
            show_source: false
            show_root_heading: true
            show_root_toc_entry: true
            show_root_full_path: false
            show_root_members_full_path: false
            show_object_full_path: false
            show_category_heading: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            signature_crossrefs: true
            separate_signature: true
            line_length: 88
            members_order: source
            group_by_category: true
            show_if_no_docstring: false
            inherited_members: false
            filters:
              - "!^_"
              - "!^__(?!(init|call|str|repr)__)"
            annotations_path: brief
  - gen-files:
     scripts:
       - docs/gen_ref_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
  - section-index

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
      title: Page contents
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: deepsentinel
      repo: deepsentinel-sdk
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra:
  version:
    provider: mike
    default: latest
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/deepsentinel
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/deepsentinel/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/deepsentinel
  analytics:
    provider: google
    property: !ENV [GOOGLE_ANALYTICS_KEY, ""]
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/thumb-up-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/thumb-down-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback! Help us improve this page by
            <a href="https://github.com/deepsentinel/deepsentinel-sdk/issues/new/?title=[Docs]&body=URL: {url}%0A%0A" target="_blank" rel="noopener">telling us what you found confusing</a>.

extra_css:
  - assets/stylesheets/extra.css

extra_javascript:
  - assets/javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: index.md
  - Quick Start: quickstart.md
  - Core Concepts:
    - concepts/index.md
    - Overview: concepts/overview.md
    - Compliance & Security: concepts/compliance.md
    - Provider Integration: concepts/providers.md
    - Configuration: concepts/configuration.md
  - Tutorials:
    - tutorials/index.md
    - Basic Integration: tutorials/basic-integration.md
    - Multiple Providers: tutorials/multiple-providers.md
    - Streaming Responses: tutorials/streaming.md
    - Compliance Setup: tutorials/compliance-setup.md
    - Error Handling: tutorials/error-handling.md
  - Guides:
    - guides/index.md
    - Best Practices: guides/best-practices.md
    - Performance Optimization: guides/performance.md
    - Migration Guide: guides/migration.md
  - API Reference:
    - reference/
  - FAQ: faq.md

# watch:
#   - src/deepsentinel
#   - docs/**/*.md

# GitHub Pages deployment settings
use_directory_urls: true
